### ISSUE TITLE
Unnecessary Dependencies Are Causing npm audit to Fail

### ISSUE THREAD

**Issue by thefringeninja** [RayEscMata/react-input-select#1]
https://github.com/rayescmata/react-input-select/commit/cd7b82578d70b9562013e00eb1ee7594ef628e9d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R460

The particular dependency is `macaddress`. This package hasn't been updated in years and I doubt it ever will.

**Comment by rayescmata** [comment]
Hi! Thanks for this! I'm not really sure how the extra dependencies got saved - but anyways, I've updated it and it no longer uses macaddress! Have a good one!
