### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jmarucha** [RayEscMata/react-input-select#2]
Out of 
`
  "dependencies": {
    "acorn-jsx": "^3.0.1",
    "ajv": "^5.2.2",
    "ajv-keywords": "^2.1.0",
    "acorn": "^5.1.1",
    "ansi-regex": "^2.1.1",
    "ansi-styles": "^2.2.1",
    "abbrev": "^1.1.0",
    "acorn-dynamic-import": "^2.0.2",
    "ansi-escapes": "^2.0.0",
    "anymatch": "^1.3.2",
    "aproba": "^1.1.2",
    "are-we-there-yet": "^1.1.4",
    "amdefine": "^1.0.1",
    "alphanum-sort": "^1.0.2",
    "align-text": "^0.1.4",
    "argparse": "^1.0.9",
    "aria-query": "^0.7.0",
    "arr-diff": "^2.0.0",
    "arr-flatten": "^1.1.0",
    "array-find-index": "^1.0.2",
    "array-includes": "^3.0.3",
    "array-union": "^1.0.2",
    "array-unique": "^0.2.1",
    "arrify": "^1.0.1",
    "array-uniq": "^1.0.3",
    "asn1": "^0.2.3",
    "asn1.js": "^4.9.1",
    "assert": "^1.4.1",
    "asap": "^2.0.6",
    "assert-plus": "^1.0.0",
    "async-each": "^1.0.1",
    "async-foreach": "^0.1.3",
    "ast-types-flow": "^0.0.7",
    "babel-code-frame": "^6.26.0",
    "asynckit": "^0.4.0",
    "aws4": "^1.6.0",
    "babel-helper-builder-binary-assignment-operator-visitor": "^6.24.1",
    "async": "^2.5.0",
    "aws-sign2": "^0.6.0",
    "babel-helper-bindify-decorators": "^6.24.1",
    "babel-helper-builder-react-jsx": "^6.26.0",
    "babel-helper-call-delegate": "^6.24.1",
    "babel-helper-define-map": "^6.26.0",
    "babel-helper-explode-assignable-expression": "^6.24.1",
    "babel-helper-explode-class": "^6.24.1",
    "babel-helper-function-name": "^6.24.1",
    "babel-helper-hoist-variables": "^6.24.1",
    "babel-helper-get-function-arity": "^6.24.1",
    "babel-helper-optimise-call-expression": "^6.24.1",
    "babel-helper-regex": "^6.26.0",
    "babel-helper-remap-async-to-generator": "^6.24.1",
    "babel-helper-replace-supers": "^6.24.1",
    "babel-plugin-syntax-async-generators": "^6.13.0",
    "autoprefixer": "^6.7.7",
    "babel-plugin-syntax-class-constructor-call": "^6.18.0",
    "babel-plugin-syntax-class-properties": "^6.13.0",
    "babel-plugin-syntax-decorators": "^6.13.0",
    "babel-messages": "^6.23.0",
    "babel-plugin-check-es2015-constants": "^6.22.0",
    "babel-plugin-syntax-export-extensions": "^6.13.0",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-syntax-do-expressions": "^6.13.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-syntax-exponentiation-operator": "^6.13.0",
    "babel-plugin-syntax-object-rest-spread": "^6.13.0",
    "babel-plugin-syntax-flow": "^6.18.0",
    "babel-plugin-syntax-function-bind": "^6.13.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-syntax-trailing-function-commas": "^6.22.0",
    "babel-plugin-transform-async-generator-functions": "^6.24.1",
    "babel-plugin-transform-do-expressions": "^6.22.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-constructor-call": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-plugin-transform-es2015-computed-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-es2015-block-scoping": "^6.26.0",
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
    "babel-plugin-transform-es2015-duplicate-keys": "^6.24.1",
    "babel-plugin-transform-es2015-for-of": "^6.23.0",
    "babel-plugin-transform-es2015-function-name": "^6.24.1",
    "babel-plugin-transform-es2015-literals": "^6.22.0",
    "babel-plugin-transform-es2015-modules-amd": "^6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-es2015-modules-systemjs": "^6.24.1",
    "babel-plugin-transform-es2015-modules-umd": "^6.24.1",
    "babel-plugin-transform-es2015-object-super": "^6.24.1",
    "babel-plugin-transform-es2015-parameters": "^6.24.1",
    "babel-plugin-transform-es2015-spread": "^6.22.0",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.24.1",
    "babel-plugin-transform-es2015-sticky-regex": "^6.24.1",
    "babel-plugin-transform-exponentiation-operator": "^6.24.1",
    "babel-plugin-transform-es2015-template-literals": "^6.22.0",
    "babel-plugin-transform-es2015-unicode-regex": "^6.24.1",
    "babel-plugin-transform-es2015-typeof-symbol": "^6.23.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-display-name": "^6.25.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "axobject-query": "^0.1.0",
    "babel-generator": "^6.26.0",
    "babel-plugin-transform-regenerator": "^6.26.0",
    "babel-plugin-transform-strict-mode": "^6.24.1",
    "babel-template": "^6.26.0",
    "babel-helpers": "^6.24.1",
    "babel-plugin-transform-react-jsx-self": "^6.22.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-flow": "^6.23.0",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "^6.18.0",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "babel-register": "^6.26.0",
    "balanced-match": "^0.4.2",
    "base64-js": "^1.2.1",
    "brace-expansion": "^1.1.8",
    "big.js": "^3.1.3",
    "bcrypt-pbkdf": "^1.0.1",
    "binary-extensions": "^1.10.0",
    "braces": "^1.8.5",
    "brorand": "^1.1.0",
    "block-stream": "^0.0.9",
    "boom": "^2.10.1",
    "browserify-aes": "^1.0.6",
    "browserify-cipher": "^1.0.0",
    "browserify-zlib": "^0.1.4",
    "browserify-rsa": "^4.0.1",
    "buffer": "^4.9.1",
    "browserify-des": "^1.0.0",
    "browserify-sign": "^4.0.4",
    "browserslist": "^1.7.7",
    "buffer-xor": "^1.0.3",
    "builtin-modules": "^1.1.1",
    "builtin-status-codes": "^3.0.0",
    "bn.js": "^4.11.8",
    "caller-path": "^0.1.0",
    "callsites": "^0.2.0",
    "camelcase": "^3.0.0",
    "chalk": "^1.1.3",
    "camelcase-keys": "^2.1.0",
    "caniuse-api": "^1.6.1",
    "caniuse-db": "^1.0.30000671",
    "caniuse-lite": "^1.0.30000718",
    "chokidar": "^1.7.0",
    "cipher-base": "^1.0.4",
    "clap": "^1.2.0",
    "center-align": "^0.1.3",
    "circular-json": "^0.3.3",
    "cli-cursor": "^2.1.0",
    "cli-width": "^2.2.0",
    "cliui": "^3.2.0",
    "co": "^4.6.0",
    "caseless": "^0.11.0",
    "clone-deep": "^0.3.0",
    "clone": "^1.0.2",
    "color-convert": "^1.9.0",
    "coa": "^1.0.4",
    "code-point-at": "^1.1.0",
    "color": "^0.11.4",
    "color-name": "^1.1.3",
    "concat-map": "^0.0.1",
    "color-string": "^0.3.0",
    "colormin": "^1.1.2",
    "commondir": "^1.0.1",
    "colors": "^1.1.2",
    "console-browserify": "^1.1.0",
    "combined-stream": "^1.0.5",
    "constants-browserify": "^1.0.0",
    "commander": "^2.11.0",
    "concat-stream": "^1.6.0",
    "contains-path": "^0.1.0",
    "create-react-class": "^15.6.0",
    "convert-source-map": "^1.5.0",
    "console-control-strings": "^1.1.0",
    "core-util-is": "^1.0.2",
    "core-js": "^2.5.0",
    "create-hmac": "^1.1.6",
    "create-ecdh": "^4.0.0",
    "crypto-browserify": "^3.11.1",
    "create-hash": "^1.1.3",
    "cross-spawn": "^5.1.0",
    "cryptiles": "^2.0.5",
    "css-color-names": "^0.0.4",
    "css-selector-tokenizer": "^0.7.0",
    "cssesc": "^0.1.0",
    "cssnano": "^3.10.0",
    "currently-unhandled": "^0.4.1",
    "csso": "^2.3.2",
    "dashdash": "^1.14.1",
    "debug": "^2.6.8",
    "decamelize": "^1.2.0",
    "damerau-levenshtein": "^1.0.4",
    "d": "^1.0.0",
    "define-properties": "^1.1.2",
    "date-now": "^0.1.4",
    "defined": "^1.0.0",
    "del": "^2.2.2",
    "delayed-stream": "^1.0.0",
    "delegates": "^1.0.0",
    "detect-indent": "^4.0.0",
    "des.js": "^1.0.0",
    "domain-browser": "^1.1.7",
    "doctrine": "^2.0.0",
    "diffie-hellman": "^5.0.2",
    "deep-is": "^0.1.3",
    "ecc-jsbn": "^0.1.1",
    "error-ex": "^1.3.1",
    "emojis-list": "^2.1.0",
    "electron-to-chromium": "^1.3.18",
    "elliptic": "^6.4.0",
    "enhanced-resolve": "^3.4.1",
    "emoji-regex": "^6.5.1",
    "encoding": "^0.1.12",
    "errno": "^0.1.4",
    "es-abstract": "^1.8.0",
    "es-to-primitive": "^1.1.1",
    "es5-ext": "^0.10.30",
    "escape-string-regexp": "^1.0.5",
    "es6-iterator": "^2.0.1",
    "es6-map": "^0.1.5",
    "es6-set": "^0.1.5",
    "es6-symbol": "^3.1.1",
    "es6-weak-map": "^2.0.2",
    "eslint-restricted-globals": "^0.1.1",
    "escope": "^3.6.0",
    "eslint-config-airbnb-base": "^11.3.2",
    "eslint-import-resolver-node": "^0.3.1",
    "esutils": "^2.0.2",
    "eslint-module-utils": "^2.1.1",
    "espree": "^3.5.0",
    "esquery": "^1.0.0",
    "esrecurse": "^4.2.0",
    "esprima": "^2.7.3",
    "estraverse": "^4.2.0",
    "events": "^1.1.1",
    "execa": "^0.7.0",
    "evp_bytestokey": "^1.0.2",
    "event-emitter": "^0.3.5",
    "expand-brackets": "^0.1.5",
    "extend": "^3.0.1",
    "expand-range": "^1.8.2",
    "fbjs": "^0.8.14",
    "external-editor": "^2.0.4",
    "extsprintf": "^1.3.0",
    "extglob": "^0.3.2",
    "fast-deep-equal": "^1.0.0",
    "find-cache-dir": "^1.0.0",
    "fast-levenshtein": "^2.0.6",
    "fastparse": "^1.1.1",
    "figures": "^2.0.0",
    "file-entry-cache": "^2.0.0",
    "filename-regex": "^2.0.1",
    "fill-range": "^2.2.3",
    "for-in": "^1.0.2",
    "for-own": "^1.0.0",
    "find-up": "^1.1.2",
    "flat-cache": "^1.2.2",
    "flatten": "^1.0.2",
    "foreach": "^2.0.5",
    "fs.realpath": "^1.0.0",
    "forever-agent": "^0.6.1",
    "fs-readdir-recursive": "^1.0.0",
    "form-data": "^2.1.4",
    "function-bind": "^1.1.1",
    "functional-red-black-tree": "^1.0.1",
    "fstream": "^1.0.11",
    "get-stream": "^3.0.0",
    "gauge": "^2.7.4",
    "gaze": "^1.1.2",
    "get-caller-file": "^1.0.2",
    "get-stdin": "^4.0.1",
    "getpass": "^0.1.7",
    "globals": "^9.18.0",
    "glob": "^7.1.2",
    "glob-base": "^0.3.0",
    "glob-parent": "^2.0.0",
    "globby": "^5.0.0",
    "graceful-fs": "^4.1.11",
    "has-ansi": "^2.0.0",
    "has-flag": "^2.0.0",
    "globule": "^1.2.0",
    "has": "^1.0.1",
    "har-validator": "^2.0.6",
    "has-unicode": "^2.0.1",
    "hash-base": "^2.0.2",
    "hash.js": "^1.1.3",
    "hawk": "^3.1.3",
    "hmac-drbg": "^1.0.1",
    "hoek": "^2.16.3",
    "home-or-tmp": "^2.0.0",
    "https-browserify": "^0.0.1",
    "hosted-git-info": "^2.5.0",
    "html-comment-regex": "^1.1.1",
    "http-signature": "^1.1.1",
    "generate-function": "^2.0.0",
    "iconv-lite": "^0.4.18",
    "generate-object-property": "^1.2.0",
    "icss-utils": "^2.1.0",
    "icss-replace-symbols": "^1.1.0",
    "ieee754": "^1.1.8",
    "imurmurhash": "^0.1.4",
    "ignore": "^3.3.5",
    "in-publish": "^2.0.0",
    "inflight": "^1.0.6",
    "inherits": "^2.0.3",
    "indent-string": "^2.1.0",
    "is-arrayish": "^0.2.1",
    "indexes-of": "^1.0.1",
    "invariant": "^2.2.2",
    "indexof": "^0.0.1",
    "invert-kv": "^1.0.0",
    "inquirer": "^3.2.2",
    "interpret": "^1.0.3",
    "is-buffer": "^1.1.5",
    "is-absolute-url": "^2.1.0",
    "is-binary-path": "^1.0.1",
    "is-builtin-module": "^1.0.0",
    "is-callable": "^1.1.3",
    "is-date-object": "^1.0.1",
    "is-dotfile": "^1.0.3",
    "is-finite": "^1.0.2",
    "is-equal-shallow": "^0.1.3",
    "is-extendable": "^0.1.1",
    "is-extglob": "^1.0.0",
    "is-fullwidth-code-point": "^1.0.0",
    "is-glob": "^2.0.1",
    "is-number": "^2.1.0",
    "is-path-cwd": "^1.0.0",
    "is-plain-object": "^2.0.4",
    "is-my-json-valid": "^2.16.1",
    "is-path-in-cwd": "^1.0.0",
    "is-path-inside": "^1.0.0",
    "is-plain-obj": "^1.1.0",
    "is-posix-bracket": "^0.1.1",
    "is-primitive": "^2.0.0",
    "is-promise": "^2.1.0",
    "is-stream": "^1.1.0",
    "is-property": "^1.0.2",
    "is-regex": "^1.0.4",
    "is-resolvable": "^1.0.0",
    "is-symbol": "^1.0.1",
    "is-svg": "^2.1.0",
    "isobject": "^3.0.1",
    "is-typedarray": "^1.0.0",
    "js-tokens": "^3.0.2",
    "is-utf8": "^0.2.1",
    "isarray": "^1.0.0",
    "isomorphic-fetch": "^2.2.1",
    "jsesc": "^1.3.0",
    "isexe": "^2.0.0",
    "isstream": "^0.1.2",
    "js-base64": "^2.1.9",
    "json-loader": "^0.5.7",
    "js-yaml": "^3.6.1",
    "jsbn": "^0.1.1",
    "jschardet": "^1.5.1",
    "json-schema": "^0.2.3",
    "json-schema-traverse": "^0.3.1",
    "json-stringify-safe": "^5.0.1",
    "json-stable-stringify": "^1.0.1",
    "jsonify": "^0.0.0",
    "json5": "^0.5.1",
    "kind-of": "^3.2.2",
    "jsonpointer": "^4.0.1",
    "lcid": "^1.0.0",
    "lazy-cache": "^0.2.7",
    "jsprim": "^1.4.1",
    "locate-path": "^2.0.0",
    "jsx-ast-utils": "^1.4.1",
    "lcov-parse": "^0.0.10",
    "lodash.assign": "^4.2.0",
    "lodash.clonedeep": "^4.5.0",
    "levn": "^0.3.0",
    "load-json-file": "^1.1.0",
    "lodash.camelcase": "^4.3.0",
    "loader-runner": "^2.3.0",
    "lodash.memoize": "^4.1.2",
    "loader-utils": "^1.1.0",
    "lodash.tail": "^4.1.1",
    "lodash.cond": "^4.5.2",
    "lodash.mergewith": "^4.6.0",
    "lodash.uniq": "^4.5.0",
    "log-driver": "^1.2.5",
    "lodash": "^4.17.4",
    "make-dir": "^1.0.0",
    "lru-cache": "^4.1.1",
    "longest": "^1.0.1",
    "loose-envify": "^1.3.1",
    "loud-rejection": "^1.6.0",
    "macaddress": "^0.2.8",
    "map-obj": "^1.0.1",
    "mem": "^1.1.0",
    "math-expression-evaluator": "^1.2.17",
    "md5.js": "^1.3.4",
    "memory-fs": "^0.4.1",
    "meow": "^3.7.0",
    "miller-rabin": "^4.0.0",
    "minimatch": "^3.0.4",
    "mimic-fn": "^1.1.0",
    "mime-types": "^2.1.16",
    "micromatch": "^2.3.11",
    "mkdirp": "^0.5.1",
    "minimist": "^1.2.0",
    "minimalistic-crypto-utils": "^1.0.1",
    "ms": "^2.0.0",
    "mute-stream": "^0.0.7",
    "mime-db": "^1.29.0",
    "mixin-object": "^2.0.1",
    "node-libs-browser": "^2.0.0",
    "natural-compare": "^1.4.0",
    "nan": "^2.7.0",
    "node-fetch": "^1.7.2",
    "normalize-package-data": "^2.4.0",
    "nopt": "^3.0.6",
    "npm-run-path": "^2.0.2",
    "minimalistic-assert": "^1.0.0",
    "node-gyp": "^3.6.2",
    "num2fraction": "^1.2.2",
    "npmlog": "^4.1.2",
    "number-is-nan": "^1.0.1",
    "normalize-path": "^2.1.1",
    "once": "^1.4.0",
    "object-assign": "^4.1.1",
    "normalize-range": "^0.1.2",
    "object-keys": "^1.0.11",
    "normalize-url": "^1.9.1",
    "oauth-sign": "^0.8.2",
    "os-browserify": "^0.2.1",
    "os-homedir": "^1.0.2",
    "os-locale": "^2.1.0",
    "p-finally": "^1.0.0",
    "p-limit": "^1.1.0",
    "p-locate": "^2.0.0",
    "object.omit": "^2.0.1",
    "os-tmpdir": "^1.0.2",
    "parse-json": "^2.2.0",
    "osenv": "^0.1.4",
    "output-file-sync": "^1.1.2",
    "pako": "^0.2.9",
    "path-is-absolute": "^1.0.1",
    "onetime": "^2.0.1",
    "path-key": "^2.0.1",
    "optionator": "^0.8.2",
    "parse-glob": "^3.0.4",
    "pify": "^2.3.0",
    "path-browserify": "^0.0.0",
    "parse-asn1": "^5.1.0",
    "path-is-inside": "^1.0.2",
    "path-exists": "^2.1.0",
    "path-parse": "^1.0.5",
    "path-type": "^1.1.0",
    "pinkie-promise": "^2.0.1",
    "pbkdf2": "^3.0.13",
    "pkg-dir": "^1.0.0",
    "pluralize": "^4.0.0",
    "postcss": "^5.2.17",
    "postcss-calc": "^5.3.1",
    "postcss-colormin": "^2.2.2",
    "postcss-convert-values": "^2.6.1",
    "postcss-discard-comments": "^2.0.4",
    "postcss-discard-duplicates": "^2.1.0",
    "postcss-discard-empty": "^2.1.0",
    "postcss-discard-unused": "^2.2.3",
    "postcss-discard-overridden": "^0.1.1",
    "postcss-merge-idents": "^2.1.7",
    "postcss-filter-plugins": "^2.0.2",
    "postcss-merge-rules": "^2.1.2",
    "postcss-merge-longhand": "^2.0.2",
    "postcss-message-helpers": "^2.0.0",
    "postcss-minify-font-values": "^1.0.5",
    "postcss-minify-gradients": "^1.0.5",
    "pinkie": "^2.0.4",
    "postcss-modules-local-by-default": "^1.2.0",
    "postcss-modules-values": "^1.3.0",
    "postcss-modules-scope": "^1.1.0",
    "postcss-normalize-charset": "^1.1.1",
    "postcss-normalize-url": "^3.0.8",
    "postcss-minify-params": "^1.2.2",
    "postcss-ordered-values": "^2.2.3",
    "postcss-reduce-initial": "^1.0.1",
    "postcss-minify-selectors": "^2.1.1",
    "postcss-reduce-idents": "^2.4.0",
    "postcss-selector-parser": "^2.2.3",
    "postcss-reduce-transforms": "^1.0.4",
    "postcss-svgo": "^2.1.6",
    "postcss-unique-selectors": "^2.0.2",
    "postcss-value-parser": "^3.3.0",
    "postcss-zindex": "^2.2.0",
    "postcss-modules-extract-imports": "^1.2.0",
    "prelude-ls": "^1.1.2",
    "private": "^0.1.7",
    "process": "^0.11.10",
    "prop-types": "^15.5.10",
    "preserve": "^0.2.0",
    "prepend-http": "^1.0.4",
    "process-nextick-args": "^1.0.7",
    "progress": "^2.0.0",
    "pseudomap": "^1.0.2",
    "promise": "^7.3.1",
    "prr": "^0.0.0",
    "punycode": "^1.4.1",
    "public-encrypt": "^4.0.0",
    "q": "^1.5.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "querystring-es3": "^0.2.1",
    "querystring": "^0.2.0",
    "randomatic": "^1.1.7",
    "query-string": "^4.3.4",
    "readable-stream": "^2.3.3",
    "react-onclickoutside": "^6.5.0",
    "randombytes": "^2.0.5",
    "read-pkg": "^1.1.0",
    "regenerate": "^1.3.2",
    "qs": "^6.3.2",
    "read-pkg-up": "^1.0.1",
    "redent": "^1.0.0",
    "readdirp": "^2.1.0",
    "regenerator-transform": "^0.10.1",
    "regjsparser": "^0.1.5",
    "reduce-css-calc": "^1.3.0",
    "regenerator-runtime": "^0.10.5",
    "regjsgen": "^0.2.0",
    "reduce-function-call": "^1.0.2",
    "regexpu-core": "^1.0.0",
    "repeat-element": "^1.1.2",
    "regex-cache": "^0.4.3",
    "repeating": "^2.0.1",
    "repeat-string": "^1.6.1",
    "require-directory": "^2.1.1",
    "require-main-filename": "^1.0.1",
    "require-uncached": "^1.0.3",
    "requireindex": "^1.1.0",
    "remove-trailing-separator": "^1.1.0",
    "resolve-from": "^1.0.1",
    "resolve": "^1.4.0",
    "restore-cursor": "^2.0.0",
    "right-align": "^0.1.3",
    "ripemd160": "^2.0.1",
    "rx-lite": "^4.0.8",
    "rx-lite-aggregates": "^4.0.8",
    "safe-buffer": "^5.1.1",
    "request": "^2.79.0",
    "sass-graph": "^2.2.4",
    "semver": "^5.4.1",
    "schema-utils": "^0.3.0",
    "setimmediate": "^1.0.5",
    "set-blocking": "^2.0.0",
    "sax": "^1.2.4",
    "shallow-clone": "^0.1.2",
    "shebang-regex": "^1.0.0",
    "set-immediate-shim": "^1.0.1",
    "scss-tokenizer": "^0.2.3",
    "sha.js": "^2.4.8",
    "slash": "^1.0.0",
    "run-async": "^2.3.0",
    "shebang-command": "^1.2.0",
    "signal-exit": "^3.0.2",
    "sntp": "^1.0.9",
    "source-list-map": "^2.0.0",
    "source-map": "^0.5.7",
    "slice-ansi": "^0.0.4",
    "sort-keys": "^1.1.2",
    "source-map-support": "^0.4.16",
    "stream-http": "^2.7.2",
    "spdx-license-ids": "^1.2.2",
    "spdx-correct": "^1.0.2",
    "string_decoder": "^0.10.31",
    "spdx-expression-parse": "^1.0.4",
    "stream-browserify": "^2.0.1",
    "sshpk": "^1.13.1",
    "stdout-stream": "^1.4.0",
    "strip-ansi": "^3.0.1",
    "string-width": "^1.0.2",
    "sprintf-js": "^1.0.3",
    "strip-eof": "^1.0.0",
    "strict-uri-encode": "^1.1.0",
    "stringstream": "^0.0.5",
    "supports-color": "^4.2.1",
    "strip-bom": "^2.0.0",
    "strip-json-comments": "^2.0.1",
    "strip-indent": "^1.0.1",
    "svgo": "^0.7.2",
    "tapable": "^0.2.8",
    "table": "^4.0.1",
    "tar": "^2.2.1",
    "text-table": "^0.2.0",
    "tmp": "^0.0.31",
    "to-fast-properties": "^1.0.3",
    "timers-browserify": "^2.0.4",
    "tough-cookie": "^2.3.2",
    "tty-browserify": "^0.0.0",
    "trim-newlines": "^1.0.0",
    "trim-right": "^1.0.1",
    "tryit": "^1.0.3",
    "tweetnacl": "^0.14.5",
    "to-arraybuffer": "^1.0.1",
    "type-check": "^0.3.2",
    "through": "^2.3.8",
    "typedarray": "^0.0.6",
    "uglify-to-browserify": "^1.0.2",
    "uniq": "^1.0.1",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "uniqid": "^4.1.1",
    "url": "^0.11.0",
    "uniqs": "^2.0.0",
    "tunnel-agent": "^0.4.3",
    "ua-parser-js": "^0.7.14",
    "util-deprecate": "^1.0.2",
    "util": "^0.10.3",
    "uuid": "^3.1.0",
    "v8flags": "^2.1.1",
    "validate-npm-package-license": "^3.0.1",
    "vendors": "^1.0.1",
    "user-home": "^1.1.1",
    "vm-browserify": "^0.0.4",
    "verror": "^1.10.0",
    "webpack-sources": "^1.0.1",
    "watchpack": "^1.4.0",
    "uglify-js": "^2.8.29",
    "whatwg-fetch": "^2.0.3",
    "which": "^1.3.0",
    "whet.extend": "^0.9.9",
    "which-module": "^2.0.0",
    "wide-align": "^1.1.2",
    "wrappy": "^1.0.2",
    "wordwrap": "^1.0.0",
    "window-size": "^0.1.0",
    "wrap-ansi": "^2.1.0",
    "write": "^0.2.1",
    "xtend": "^4.0.1",
    "y18n": "^3.2.1",
    "yallist": "^2.1.2",
    "yargs": "^8.0.2",
    "eslint-scope": "^3.7.1",
    "yargs-parser": "^7.0.0"
}
`
in dependencies only `react`, `react-dom` and `react-onclickoutside` seem to be used.

**Comment by rayescmata** [comment]
I'm not really sure how this happened, but thanks for this! I've cleaned it up in 1.0.3!
